---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Install build-essential
  action: apt pkg=build-essential
  become: true

- name: Remove old go bin directory
  file:
    path: "{{ ansible_env.HOME }}/.go"
    state: absent

- name: Download go installer
  get_url:
    url: https://raw.githubusercontent.com/maticnetwork/node-ansible/master/go-install.sh
    dest: "{{ ansible_env.HOME }}/go-install.sh"
    mode: '0755'

- name: Execute the go-install.sh
  command: "bash go-install.sh"
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Remove the go-install.sh
  file:
    path: "{{ ansible_env.HOME }}/go-install.sh"
    state: absent

- name: Creating symlink for golang
  file:
    src: "{{ ansible_env.HOME }}/.go/bin/go"
    dest: "/usr/bin/go"
    state: link
  become: true

- name: Install jq
  action: apt pkg=jq
  become: true

- name: Install git
  action: apt pkg=git
  become: true

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present
  become: true
