---
- name: Cloning the Bor
  git:
    repo: "https://github.com/maticnetwork/bor.git"
    dest: "{{ ansible_env.HOME }}/bor"
    force: yes
    version: "{{ bor_branch }}"

- name: Build Bor
  command: chdir={{ ansible_env.HOME }}/bor make bor

- name: Copy bor
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/bor/build/bin/bor"
    dest: "/usr/local/bin/bor"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  become: true