---
- name: Setup Heimdall service
  copy:
    src: "{{ ansible_env.HOME }}/heimdall/builder/files/heimdalld.service"
    dest: /lib/systemd/system/heimdalld.service
    mode: "0644"
    remote_src: true
  notify: reload heimdalld
  become: true
  tags:
    - heimdall

- name: Ensure /etc/systemd/system/heimdalld.service.d/ exists
  file:
    path: /etc/systemd/system/heimdalld.service.d/
    state: directory
  become: true

- name: Customize Heimdall service
  copy:
    dest: /etc/systemd/system/heimdalld.service.d/override.conf
    mode: "0644"
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/local/bin/heimdalld start --home /mnt/rpc/heimdall --chain=mainnet --rest-server
  notify: reload heimdalld
  become: true
  tags:
    - heimdall

- name: Setup Bor service
  copy:
    src: "{{ ansible_env.HOME }}/bor/builder/files/bor.service"
    dest: /lib/systemd/system/bor.service
    mode: "0644"
    remote_src: true
  notify: reload bor
  become: true
  tags:
    - bor

- name: Ensure /etc/systemd/system/bor.service.d/ exists
  file:
    path: /etc/systemd/system/bor.service.d/
    state: directory
  become: true

- name: Customize Bor service
  copy:
    dest: /etc/systemd/system/bor.service.d/override.conf
    mode: "0644"
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/local/bin/bor server -config "/mnt/rpc/bor/config.toml"
  notify: reload bor
  become: true
  tags:
    - bor

- name: Create /etc/matic directory
  file:
    path: /etc/matic
    state: directory
  become: true

- name: Ensure group "bor" exists
  ansible.builtin.group:
    name: bor
    state: present
  become: true

- name: Ensure user 'bor' exists
  ansible.builtin.user:
    name: bor
    group: bor
    shell: /bin/bash
  become: true

- name: Ensure group "heimdall" exists
  ansible.builtin.group:
    name: heimdall
    state: present
  become: true

- name: Ensure user 'heimdall' exists
  ansible.builtin.user:
    name: heimdall
    group: heimdall
    shell: /bin/bash
  become: true